export const DEFAULT_INTEREST_TOPICS = [
  'Tecnologia',
  'Anime',
  'Música',
  'Horror',
  'Livros',
  'Economia',
  'Games',
  'Filmes e Séries',
  'Entretenimento',
  'Educação',
  'Brasil',
  'Mundo',
  'Política',
  'Ciência',
  'Carros',
  'Cultura',
  'Turismo',
  'E-sports',
  'Agronegócio',
  'Viagens',
  'Carnaval',
  'Inteligência Artificial',
  'Empreendedorismo',
] as const
